[package]
name = "linesweeper-py"
version = "0.2.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "linesweeper"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.27.0"
linesweeper = "0.3.0"
kurbo = "0.13.0" # Must use same version as linesweeper
